version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network
      
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend-network


networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  db-data:
